services:
  postgres:
    image: postgres:16
    container_name: jarvis_postgres
    environment:
      POSTGRES_DB: jarvis_db
      POSTGRES_USER: jarvis
      POSTGRES_PASSWORD: jarvis123
    ports:
      - "5432:5432"
    volumes:
      - jarvis_postgres_data:/var/lib/postgresql/data

volumes:
  jarvis_postgres_data:

